### ISSUE TITLE
I'm trying to download the tile-replicator from this link

### ISSUE THREAD

**Issue by wxlund** [pivotal-cf/docs-rabbitmq-pcf#153]
When I follow the guide: 

> The RabbitMQ for PCF Replicator is currently available from [Pivotal Network](https://network.pivotal.io). Search for and download this archive, and then run the enclosed binary. 
> 
I'm unable to find the tile replicator.  Is it not out on Pivnet yet?

**Comment by kdudala1** [comment]
Hi Wayne,

Replicator is currently available for RMQ for PCF 1.8 and 1.9. We're adding
1.10 support soon. Can you check in the Pivnet folder for RMQ for PCF 1.9
or 1.8 and let us know if you don't see the binary? It should be located
alongside the RMQ for PCF tile.

Thanks,
Kal

**Comment by wxlund** [comment]
I see it fine in the older release.  Thx
