### ISSUE TITLE
Rabbit MQ for PCF - no instructions for the credentials

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-rabbitmq-pcf#226]
Im referring to the Rabbit MQ installation docs to setup Rabbit MQ - on demand configuration to get Federation working. 

The docs don't specify anything about the admin credentials. The Ops manager console has a mandatory entry for the admin credentials as shown below. 

<img width="731" alt="screen shot 2018-02-26 at 7 21 26 pm" src="https://user-images.githubusercontent.com/32221454/36703647-91c75824-1b2a-11e8-80ec-89d4dc643987.png">

The docs here indicates that only metrics configuration is to be set on this tab. 
http://docs.pivotal.io/rabbitmq-cf/1-11/install-config.html#tile_configurations

**Comment by msathe-tech** [comment]
<img width="748" alt="screen shot 2018-02-26 at 7 41 09 pm" src="https://user-images.githubusercontent.com/32221454/36704146-0a87b612-1b2d-11e8-8b36-42af29e726e8.png">

**Comment by mkuratczyk** [comment]
These credentials will become the admin credentials of the multitenant cluster. If you don't intend to use multitenant service unfortunately you still need to specify something in these fields but you can set the number of VMs to 0 in the Resource Config section. For on-demand services, admin credentials are automatically generated when you bind to a service. We'll update the documentation to explain this better.

**Comment by ghanna2017** [comment]
I've added the instructions to provide admin creds for the on-demand service here: http://docs-pcf-staging.cfapps.io/rabbitmq-cf/1-11/install-config.html#polling. It'll be in production shortly.

**Comment by ghanna2017** [comment]
I've added the instructions to provide admin creds for the on-demand service here: http://docs-pcf-staging.cfapps.io/rabbitmq-cf/1-11/install-config.html#polling. It'll be in production shortly.
