### ISSUE TITLE
upgrade path is incorrect

### ISSUE THREAD

**Issue by ywei2017** [pivotal-cf/docs-rabbitmq-pcf#472]
The document says you can upgrade directly from 1.15 to 1.17. That is not the case. When I tried to stage the 1.17 tile, I got the following message in OpsMgr
`This upgrade requires that the currently installed version be 1.16.0 or higher.`

Thanks
Yansheng

**Comment by RichardJJG** [comment]
Thank you for this feedback, @ywei2017. I've asked the engineers to assist.

**Comment by ferozjilla** [comment]
Hi @ywei2017, you are absolutely right!

We intended for the current version of 1.17 to be upgradable from 1.15, but the changes have ended up going into the next version (of 1.17) which we plan on releasing soon. 

We will update the docs to reflect the exact version from which this upgrade is possible.

Thanks for bringing it up :)

**Comment by coro** [comment]
We've made a PR with the fix for this issue: https://github.com/pivotal-cf/docs-rabbitmq-pcf/pull/473
