### ISSUE TITLE
Branding change lists PCF rather than Pivotal Platform

### ISSUE THREAD

**Issue by edbyford** [pivotal-cf/docs-rabbitmq-pcf#495]
Hi, this line appears to be incorrect:

https://github.com/pivotal-cf/docs-rabbitmq-pcf/blob/aed2840583eaf7f685610e08f0a5595c6d8294ab/releases.html.md.erb#L6

![image](https://user-images.githubusercontent.com/5754823/69974687-a8e47200-151d-11ea-8f42-9951d0fee9bd.png)

**Comment by snneji** [comment]
Hi @edbyford, thanks for spotting this. It should be fixed now:http://docs-pcf-staging.cfapps.io/rabbitmq-cf/1-n/
