### ISSUE TITLE
Cherry pick Rolling Upgrades

### ISSUE THREAD

**Issue by edbyford** [pivotal-cf/docs-rabbitmq-pcf#510]
Hi team

Please can we cherry pick this https://github.com/pivotal-cf/docs-rabbitmq-pcf/blob/master/rolling-upgrade.html.md.erb to v1.17 and v1.18 also?

**Comment by radaeze** [comment]
@edbyford Thanks for flagging this! The page is now on the production in 1.17 and 1.18

https://docs.pivotal.io/rabbitmq-cf/1-18/rolling-upgrade.html
https://docs.pivotal.io/rabbitmq-cf/1-17/rolling-upgrade.html
