### ISSUE TITLE
Repeat this warning on login route across 1.18.x versions 

### ISSUE THREAD

**Issue by edbyford** [pivotal-cf/docs-rabbitmq-pcf#534]
https://github.com/pivotal-cf/docs-rabbitmq-pcf/blob/2769da234312d97d251216adece6faeb73bddbb0/releases.html.md.erb#L616

Hi folks

The above warning isn't repeated across other 1.18 minor versions. When customers upgrade, they can [run into issues](https://pivotal.slack.com/archives/C0RDGG81Z/p1594743113093200) unless they read the release notes for this version.

Please can this be resolved?

**Comment by coro** [comment]
Closing as 1.18.x is EOGS
