### ISSUE TITLE
Refers to another tile version

### ISSUE THREAD

**Issue by edbyford** [pivotal-cf/docs-rabbitmq-pcf#593]
https://github.com/pivotal-cf/docs-rabbitmq-pcf/blob/93286dece3c03c4209a4d63429803d2711e20ef7/releases.html.md.erb#L229

This snippet talks about functionality available in next version

**Comment by snneji** [comment]
Looks like a typo. I think the feature was copied from 1.21.0 without changing the version number. Both 1.21.0 and 1.20.3 went out at the same time.

I changed the version number to match the release: https://github.com/pivotal-cf/docs-rabbitmq-pcf/commit/138779d132cf3a936a2c372caa682fe73442f7f7

Thanks for noticing!
