### ISSUE TITLE
issue in indentation of yaml for prometheus scraping job

### ISSUE THREAD

**Issue by vrabbi** [pivotal-cf/docs-rabbitmq-pcf#604]
https://github.com/pivotal-cf/docs-rabbitmq-pcf/blob/be81ced1e850a53dff6a612fea3e0ca6b0b3ad10/monitor.html.md.erb#L337

The YAML for the scraping job is not valid and is completely messed up in terms of indentations and does not work when copying and pasting into Healthwatch v2 tile.

**Comment by snneji** [comment]
Thanks for letting us know about this issue. The documentation has been updated. Indentation fixed in #605.
