### ISSUE TITLE
Metrics names have changed in 2.0

### ISSUE THREAD

**Issue by ablease** [pivotal-cf/docs-rabbitmq-pcf#611]
In 1.x Tile series we get metrics from the RabbitMQ management API. In Tile 2.x we get metrics from the RabbitMQ prometheus endpoint.  As a result the names of some of the metrics have changed. 

In the 2.0 we should be very clear that the metrics names have all changed, and provide information for the new metrics names. 

We should also include that  object level metrics are off by default.

VMWare Tanzu RabbitMQ for VMs docs https://docs.pivotal.io/rabbitmq-cf/2-0/monitor.html

RabbitMQ Prometheus metrics. https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/metrics.md

**Comment by ablease** [comment]
Hi @snneji @RichardJJG i think we can close this. I've looked over the monitor page and can't notice anything glaringly wrong. I'll happily reopen this if I am proved wrong! :)

**Comment by snneji** [comment]
Thank you!
