### ISSUE TITLE
Firewall modification for RabbitMQ Service Broker

### ISSUE THREAD

**Issue by sudhindrarao** [pivotal-cf/docs-rabbitmq-pcf#98]
Need documentation when deploying RabbitMQ in a seperate services network.  RabbitMQ Service broker - which runs on port 4567,  should be able to access from Pivotal ERT.  Firwall policy needs to be changed to allow access from ERT -> RabbitMQ Service Broker port 4567.

**Comment by jghiloni** [comment]
+1

**Comment by bentarnoff** [comment]
Hey @sudhindrarao and @jghiloni thanks for bringing this to our attention. @davidhiston can you comment on this?

**Comment by ljarzynski** [comment]
@scottmuc Noticed this has gone stale and wanted to get your opinion

**Comment by scottmuc** [comment]
@sudhindrarao @ljarzynski the relationship from what I understand is that it looks like this: http://docs.pivotal.io/pivotalcf/1-9/services/overview.html

The ports that would need to be open (depending on the protocols enabled) would follow what's listed in the **Security Groups** section here: http://docs.pivotal.io/rabbitmq-cf/1-7/configuring.html

**Comment by ljarzynski** [comment]
@sudhindrarao Do you still feel the documentation needs to be updated given Scott's response? Or should I close out this issue?

**Comment by pspinrad** [comment]
@sudhindrarao via Slack sez all good-- closing.
